name: SwiftyLab/setup-swift

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, windows-2025-arm]
        channel: [release, dev-snapshot]
        include:
          - channel: release
            swift-version: "6.3.1"
            development: "false"
          - channel: dev-snapshot
            swift-version: ""
            development: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Swift via SwiftyLab/setup-swift (release)
        if: matrix.channel == 'release'
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Setup Swift via SwiftyLab/setup-swift (dev snapshot)
        if: matrix.channel == 'dev-snapshot'
        uses: SwiftyLab/setup-swift@latest
        with:
          development: true

      - name: swift --version
        run: swift --version

      - name: swift build
        run: swift build -c release

      - name: swift run
        run: swift run -c release Hello
